const bookItems = [
  { group: "instrument", art: "uku", no: 1, title: "고쌤의 왕왕초보 우쿨렐레", url: "https://onbook.douclass.com/bookDetail/201282" },
  { group: "instrument", art: "uku", no: 2, title: "알로하모니 01 : 우쿨렐레 타브 연주곡집", url: "https://onbook.douclass.com/bookDetail/201307" },
  { group: "instrument", art: "uku", no: 3, title: "퇴근 후 칼림바", url: "https://onbook.douclass.com/bookDetail/201308" },
  { group: "instrument", art: "uku", no: 4, title: "뉴에이지 재즈피아노 연주곡집 피아노 소곡집 1", url: "https://onbook.douclass.com/bookDetail/202084" },
  { group: "instrument", art: "uku", no: 5, title: "초짜를 위한 팝 피아노 반주법 vol.1", url: "https://onbook.douclass.com/bookDetail/202070" },
  { group: "instrument", art: "uku", no: 6, title: "어썸기타 튜토리얼", url: "https://onbook.douclass.com/bookDetail/201985" },
  { group: "instrument", art: "uku", no: 7, title: "어썸드럼 튜토리얼", url: "https://onbook.douclass.com/bookDetail/202026" },
  { group: "instrument", art: "uku", no: 8, title: "어썸보컬 튜토리얼", url: "https://onbook.douclass.com/bookDetail/202027" },
  { group: "instrument", art: "uku", no: 9, title: "한국형 엘 시스테마 : 아동·청소년 오케스트라 일궈가기", url: "https://onbook.douclass.com/bookDetail/201300" },
  { group: "instrument", art: "uku", no: 10, title: "THE CHORUS : 초등학교 합창단 운영 멘토링", url: "https://onbook.douclass.com/bookDetail/201286" },
  { group: "genre", art: "classic", no: 1, title: "잘나가는 모차르트 개런티는 얼마일까?", url: "https://onbook.douclass.com/bookDetail/201305", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 2, title: "베토벤 : 운명을 뛰어넘은 불멸의 음악가 - 웅진 생각쟁이 인물 28", url: "https://onbook.douclass.com/bookDetail/202144", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 3, title: "송사비의 클래식 음악야화 : 밤에 읽는 클래식 이야기", url: "https://onbook.douclass.com/bookDetail/201292", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 4, title: "쓸모 있는 음악책 : 내 삶을 최적화하는 상황별 음악 사용법", url: "https://onbook.douclass.com/bookDetail/201907", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 5, title: "이토록 재밌는 음악 이야기", url: "https://onbook.douclass.com/bookDetail/201287", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 6, title: "친절한 음악책", url: "https://onbook.douclass.com/bookDetail/201295", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 7, title: "한 권으로 배우는 음악 이야기", url: "https://onbook.douclass.com/bookDetail/201956", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 8, title: "음악이 아이에게 말을 걸다", url: "https://onbook.douclass.com/bookDetail/201901", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 9, title: "클래식 음악에 말걸기", url: "https://onbook.douclass.com/bookDetail/201315", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 10, title: "가곡의 탄생", url: "https://onbook.douclass.com/bookDetail/202129", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 11, title: "해설이 있는 클래식 : 서곡과 관현악곡", url: "https://onbook.douclass.com/bookDetail/201312", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 12, title: "금난새의 교향곡 여행", url: "https://onbook.douclass.com/bookDetail/201309", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 13, title: "금난새의 오페라 여행 : 오페라 여행을 위한 단 한 권의 완벽 가이드", url: "https://onbook.douclass.com/bookDetail/201310", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 14, title: "호두까기 인형 : 차이코프스키 발레극", url: "https://onbook.douclass.com/bookDetail/201297", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 15, title: "발레 음악 산책", url: "https://onbook.douclass.com/bookDetail/201311", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 16, title: "클래식 악기 이야기", url: "https://onbook.douclass.com/bookDetail/201299", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 17, title: "아홉 살에 처음 만나는 오케스트라", url: "https://onbook.douclass.com/bookDetail/201304", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 18, title: "소리를 찾아라!", url: "https://onbook.douclass.com/bookDetail/100190", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 19, title: "초등과학Q 3 빛과 소리의 세계 : 드라큘라의 비밀 수업", url: "https://onbook.douclass.com/bookDetail/200832", scope: "서양 음악" },
  { group: "genre", art: "classic", no: 20, title: "서양 음악 용어 사전 (MUSIC All that guide 3)", url: "https://onbook.douclass.com/bookDetail/201303", scope: "서양 음악" },
  { group: "genre", art: "korean", no: 1, title: "세계가 반한 우리 무형 문화재", url: "https://onbook.douclass.com/bookDetail/201091", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 2, title: "신통방통 지혜가 담긴 우리의 세시 풍속과 전통놀이", url: "https://onbook.douclass.com/bookDetail/201026", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 3, title: "하늘을 부르는 음악 종묘제례악", url: "https://onbook.douclass.com/bookDetail/201306", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 4, title: "그림으로 보는 세종 대왕", url: "https://onbook.douclass.com/bookDetail/201290", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 5, title: "만화로 보는 우리의 전통 예술", url: "https://onbook.douclass.com/bookDetail/201615", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 6, title: "만화로 보는 신명나는 우리나라 전통 음악", url: "https://onbook.douclass.com/bookDetail/201125", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 7, title: "딩덩 덩 둥덩 가야금 소리 들어 볼래?", url: "https://onbook.douclass.com/bookDetail/201302", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 8, title: "전통문화 바라보기", url: "https://onbook.douclass.com/bookDetail/201288", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 9, title: "스토리텔링으로 만나는 우리문화유산 이야기", url: "https://onbook.douclass.com/bookDetail/201059", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 10, title: "김승국의 국악, 아는 만큼 즐겁다", url: "https://onbook.douclass.com/bookDetail/202051", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 11, title: "창극, 파리와 통하다", url: "https://onbook.douclass.com/bookDetail/201285", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 12, title: "우리 소리는 좋은 것이여", url: "https://onbook.douclass.com/bookDetail/200352", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 13, title: "흥부 놀부", url: "https://onbook.douclass.com/bookDetail/200052", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 14, title: "흥보가 vs 흥보전 (같은 인물, 다른 작품! 동시에 읽는 소설)", url: "https://onbook.douclass.com/bookDetail/200435", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 15, title: "토끼전", url: "https://onbook.douclass.com/bookDetail/202112", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 16, title: "수궁가 vs 토끼전 (같은 인물, 다른 작품! 동시에 읽는 소설)", url: "https://onbook.douclass.com/bookDetail/200423", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 17, title: "춘향전", url: "https://onbook.douclass.com/bookDetail/201929", scope: "국악과 전통" },
  { group: "genre", art: "korean", no: 18, title: "춘향전·춘향가", url: "https://onbook.douclass.com/bookDetail/200446", scope: "국악과 전통" },
  { group: "genre", art: "pop", no: 1, title: "365일 팝 음악사", url: "https://onbook.douclass.com/bookDetail/202075", scope: "대중음악" },
  { group: "genre", art: "pop", no: 2, title: "비틀즈 - 살림지식총서 255", url: "https://onbook.douclass.com/bookDetail/201960", scope: "대중음악" },
  { group: "genre", art: "pop", no: 3, title: "팝의 제왕, 마이클 잭슨 : 스릴러로 시작한 팝의 황제 이야기", url: "https://onbook.douclass.com/bookDetail/202113", scope: "대중음악" },
  { group: "genre", art: "pop", no: 4, title: "한국 대중음악사: 통기타에서 하드코어까지", url: "https://onbook.douclass.com/bookDetail/202005", scope: "대중음악" },
  { group: "genre", art: "pop", no: 5, title: "K-POP 케이팝 성공방정식 : 그들은 어떻게 한국의 미래가 되었나?", url: "https://onbook.douclass.com/bookDetail/202018", scope: "대중음악" },
  { group: "genre", art: "pop", no: 6, title: "O.S.T.코드;히든 씬 : 클래식 음악이 들려주는 영화 속 숨은 이야기", url: "https://onbook.douclass.com/bookDetail/201301", scope: "대중음악" },
  { group: "genre", art: "pop", no: 7, title: "힙합은 어떻게 힙하게 됐을까?", url: "https://onbook.douclass.com/bookDetail/201289", scope: "대중음악" },
  { group: "career", art: "career", no: 1, title: "스마트폰으로 사진 편집하고 동영상 만들기", url: "https://onbook.douclass.com/bookDetail/200897" },
  { group: "career", art: "career", no: 2, title: "피아노로 배우는 왕기초 음악 이론 : 도부터 배우고 싶은 분들을 위한", url: "https://onbook.douclass.com/bookDetail/201283" },
  { group: "career", art: "career", no: 3, title: "실용음악 기초 화성학 : 한 권으로 끝내는", url: "https://onbook.douclass.com/bookDetail/201861" },
  { group: "career", art: "career", no: 4, title: "작곡독학 가이드북 : 크리에이터 박터틀의", url: "https://onbook.douclass.com/bookDetail/201291" },
  { group: "career", art: "career", no: 5, title: "교실 속 AI 교육 1 : 4차 산업 시대의 스마트한 수업 방법", url: "https://onbook.douclass.com/bookDetail/201284" },
  { group: "career", art: "career", no: 6, title: "국악에 기술 한 방울 : 4차 산업혁명 시대의 전통음악", url: "https://onbook.douclass.com/bookDetail/201296" },
  { group: "career", art: "career", no: 7, title: "인공지능과 음악 : 대한민국 1호 AI 뮤직 컨설턴트의 미래 음악 이야기", url: "https://onbook.douclass.com/bookDetail/201294" },
  { group: "career", art: "career", no: 8, title: "다빈치가 된 알고리즘 : 인공지능, 예술을 계산할 수 있을까?", url: "https://onbook.douclass.com/bookDetail/201562" },
  { group: "career", art: "career", no: 9, title: "리얼 작곡가, 작사가, 프로듀서 : 청소년을 위한 진짜 진학 진로 직업 멘토링 시리즈 3", url: "https://onbook.douclass.com/bookDetail/201298" },
  { group: "career", art: "career", no: 10, title: "음악, 당신에게 무엇입니까", url: "https://onbook.douclass.com/bookDetail/201293" },
];
