const videoItems = [
  { group: "anim", scope: "초등 음악", art: "kid", no: 1, title: "공연 관람 예절", url: "https://www.douclass.com/viewer/SPC_P/54573", len: "1:21" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 2, title: "학습 발표회장에서 지켜야 할 질서", url: "https://www.douclass.com/viewer/SPC_P/54574", len: "1:08" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 3, title: "역할 모델이란", url: "https://www.douclass.com/viewer/SPC_P/54576", len: "1:53" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 4, title: "어깨동무(번갈아 뛰기)", url: "https://www.douclass.com/viewer/SPC_P/54578", len: "0:19" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 5, title: "어깨동무(원 모양 만들기)", url: "https://www.douclass.com/viewer/SPC_P/54580", len: "0:15" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 6, title: "어깨동무(한 줄 기차놀이)", url: "https://www.douclass.com/viewer/SPC_P/54581", len: "0:14" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 7, title: "남생아 놀아라(앞소리꾼이 이끌며 놀기)", url: "https://www.douclass.com/viewer/SPC_P/54583", len: "1:52" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 8, title: "남생이 놀아라(노랫말 바꾸어 놀기)", url: "https://www.douclass.com/viewer/SPC_P/54584", len: "2:06" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 9, title: "대문놀이", url: "https://www.douclass.com/viewer/SPC_P/54587", len: "2:58" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 10, title: "해야 해야 나오너라(해 정하기 놀이)", url: "https://www.douclass.com/viewer/SPC_P/54589", len: "1:38" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 11, title: "우리 집(우리 집 놀이)", url: "https://www.douclass.com/viewer/SPC_P/54592", len: "2:15" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 12, title: "빙빙 돌아라(모여라 놀이)", url: "https://www.douclass.com/viewer/SPC_P/54594", len: "2:11" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 13, title: "빙빙 돌아라(기차 잇기 놀이)", url: "https://www.douclass.com/viewer/SPC_P/54595", len: "0:57" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 14, title: "안녕(가위바위보 인사 놀이)", url: "https://www.douclass.com/viewer/SPC_P/54596", len: "1:12" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 15, title: "안녕(문 열어라 인사 놀이)", url: "https://www.douclass.com/viewer/SPC_P/54597", len: "1:26" },
  { group: "anim", scope: "초등 음악", art: "kid", no: 16, title: "플립 플롭 믹서(미국 민속 춤)", url: "https://www.douclass.com/viewer/SPC_P/54598", len: "1:48" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 1, title: "복식 호흡하기", url: "https://www.douclass.com/viewer/SPC_P/56405", len: "0:17" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 2, title: "노래 부르기 위한 준비 운동", url: "https://www.douclass.com/viewer/SPC_P/56401", len: "2:05" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 3, title: "올바른 가창을 위한 몸과 목의 긴장 풀기", url: "https://www.douclass.com/viewer/SPC_P/56411", len: "0:19" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 4, title: "우리의 아리랑을 찾아서", url: "https://www.douclass.com/viewer/SPC_P/60509", len: "0:26" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 5, title: "민요를 부르는 방법", url: "https://www.douclass.com/viewer/SPC_P/56403", len: "0:27" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 6, title: "장구", url: "https://www.douclass.com/viewer/SPC_P/56417", len: "0:44" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 7, title: "정간보", url: "https://www.douclass.com/viewer/SPC_P/56419", len: "0:52" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 8, title: "말붙임새", url: "https://www.douclass.com/viewer/SPC_P/56402", len: "0:25" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 9, title: "토리", url: "https://www.douclass.com/viewer/SPC_P/56423", len: "0:25" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 10, title: "우리의 토리를 찾아서", url: "https://www.douclass.com/viewer/SPC_P/56412", len: "6:38" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 11, title: "시조", url: "https://www.douclass.com/viewer/SPC_P/56407", len: "0:29" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 12, title: "시조 장단", url: "https://www.douclass.com/viewer/SPC_P/56408", len: "0:33" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 13, title: "'비목' 작곡 배경", url: "https://www.douclass.com/viewer/SPC_P/56406", len: "0:19" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 14, title: "낭만주의 시대 피아노의 인기", url: "https://www.douclass.com/viewer/SPC_P/56400", len: "0:23" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 15, title: "인상주의 미술과 음악", url: "https://www.douclass.com/viewer/SPC_P/56416", len: "0:35" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 16, title: "'합창' 교향곡을 처음 연주하던 날", url: "https://www.douclass.com/viewer/SPC_P/56425", len: "0:36" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 17, title: "오페라 '마탄의 사수' 등장인물", url: "https://www.douclass.com/viewer/SPC_P/56410", len: "0:38" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 18, title: "지휘", url: "https://www.douclass.com/viewer/SPC_P/56421", len: "1:32" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 19, title: "저작권", url: "https://www.douclass.com/viewer/SPC_P/60510", len: "0:41" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 20, title: "나만의 변형 장단 만들기", url: "https://www.douclass.com/viewer/SPC_P/60511", len: "0:26" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 21, title: "장단에 어울리는 말붙임새 만들기", url: "https://www.douclass.com/viewer/SPC_P/60216", len: "2:20" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 22, title: "한도막 형식 악곡 만들기", url: "https://www.douclass.com/viewer/SPC_P/60512", len: "0:29" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 23, title: "간단한 동요 만들기", url: "https://www.douclass.com/viewer/SPC_P/60515", len: "0:22" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 24, title: "변주곡 만들기", url: "https://www.douclass.com/viewer/SPC_P/60516", len: "0:27" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 25, title: "음악극 만들기 - ①기획하기", url: "https://www.douclass.com/viewer/SPC_P/56413", len: "0:27" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 26, title: "음악극 만들기 - ②준비 및 연습하기", url: "https://www.douclass.com/viewer/SPC_P/56414", len: "2:08" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 27, title: "음악극 만들기 - ③예행 연습하기", url: "https://www.douclass.com/viewer/SPC_P/56415", len: "0:35" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 28, title: "안전한 공연 관람 방법", url: "https://www.douclass.com/viewer/SPC_P/56409", len: "1:08" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 29, title: "나도 노래를 잘 부르고 싶어", url: "https://www.douclass.com/viewer/SPC_P/60517", len: "0:55" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 30, title: "나는 아름다운 소리로 노래 부르고 있을까", url: "https://www.douclass.com/viewer/SPC_P/60542", len: "0:57" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 31, title: "노랫말과 가락의 관계", url: "https://www.douclass.com/viewer/SPC_P/60519", len: "0:27" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 32, title: "민요의 특징을 살려 노래 부르기", url: "https://www.douclass.com/viewer/SPC_P/60520", len: "0:35" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 33, title: "정간보 알아보기", url: "https://www.douclass.com/viewer/SPC_P/60534", len: "0:42" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 34, title: "랩 해요", url: "https://www.douclass.com/viewer/SPC_P/60544", len: "0:29" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 35, title: "음악의 다양한 연주 형태", url: "https://www.douclass.com/viewer/SPC_P/60533", len: "0:20" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 36, title: "&quot;나의 조국&quot; 중 '몰다우'", url: "https://www.douclass.com/viewer/SPC_P/60539", len: "13:24" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 37, title: "청소년을 위한 관현악 입문 제1부", url: "https://www.douclass.com/viewer/SPC_P/60523", len: "6:50" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 38, title: "청소년을 위한 관현악 입문 제2부", url: "https://www.douclass.com/viewer/SPC_P/60526", len: "12:04" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 39, title: "청소년을 위한 관현악 입문(악기군별 합주)", url: "https://www.douclass.com/viewer/SPC_P/60528", len: "4:50" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 40, title: "청소년을 위한 관현악 입문(악기별 변주)", url: "https://www.douclass.com/viewer/SPC_P/60530", len: "13:13" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 41, title: "종묘 제례악의 유래", url: "https://www.douclass.com/viewer/SPC_P/60215", len: "0:50" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 42, title: "오돌또기의 전설", url: "https://www.douclass.com/viewer/SPC_P/60214", len: "1:04" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 43, title: "한마음으로 만드는 응원 구호", url: "https://www.douclass.com/viewer/SPC_P/60521", len: "0:30" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 44, title: "한도막 형식의 가락 만들기", url: "https://www.douclass.com/viewer/SPC_P/60522", len: "0:34" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 45, title: "시를 노래해요", url: "https://www.douclass.com/viewer/SPC_P/60535", len: "0:26" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 46, title: "정간보에 담은 나의 가락", url: "https://www.douclass.com/viewer/SPC_P/60537", len: "0:36" },
  { group: "anim", scope: "중등 음악", art: "teen", no: 47, title: "알쏭달쏭 저작권", url: "https://www.douclass.com/viewer/SPC_P/60546", len: "1:26" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 1, title: "아람쌈쌈", url: "https://www.douclass.com/viewer/SPC_P/54629", len: "1:07" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 2, title: "올챙이와 개구리", url: "https://www.douclass.com/viewer/SPC_P/54599", len: "1:55" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 3, title: "텔레비전", url: "https://www.douclass.com/viewer/SPC_P/54600", len: "1:41" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 4, title: "퐁당퐁당", url: "https://www.douclass.com/viewer/SPC_P/54601", len: "2:43" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 5, title: "달팽이 집", url: "https://www.douclass.com/viewer/SPC_P/54602", len: "1:42" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 6, title: "꼬마 눈사람", url: "https://www.douclass.com/viewer/SPC_P/54603", len: "1:11" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 7, title: "가을 바람", url: "https://www.douclass.com/viewer/SPC_P/54604", len: "1:47" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 8, title: "잠보(안녕 반가워요)", url: "https://www.douclass.com/viewer/SPC_P/54605", len: "2:25" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 9, title: "어깨동무", url: "https://www.douclass.com/viewer/SPC_P/54606", len: "3:47" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 10, title: "소리개 떴다", url: "https://www.douclass.com/viewer/SPC_P/54607", len: "0:42" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 11, title: "대문놀이", url: "https://www.douclass.com/viewer/SPC_P/54608", len: "2:06" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 12, title: "우리 형제", url: "https://www.douclass.com/viewer/SPC_P/54610", len: "1:33" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 13, title: "아리랑", url: "https://www.douclass.com/viewer/SPC_P/54611", len: "1:44" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 14, title: "목도소리", url: "https://www.douclass.com/viewer/SPC_P/54609", len: "0:35" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 15, title: "친구하고", url: "https://www.douclass.com/viewer/SPC_P/54612", len: "1:56" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 16, title: "친구하고 마주 보고", url: "https://www.douclass.com/viewer/SPC_P/54613", len: "2:39" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 17, title: "정다운 이웃", url: "https://www.douclass.com/viewer/SPC_P/54614", len: "0:57" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 18, title: "우리 집", url: "https://www.douclass.com/viewer/SPC_P/54615", len: "3:12" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 19, title: "장사꾼 노래", url: "https://www.douclass.com/viewer/SPC_P/54616", len: "0:36" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 20, title: "안녕", url: "https://www.douclass.com/viewer/SPC_P/54617", len: "1:57" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 21, title: "봄비", url: "https://www.douclass.com/viewer/SPC_P/54618", len: "1:27" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 22, title: "나비 노래", url: "https://www.douclass.com/viewer/SPC_P/54619", len: "1:20" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 23, title: "눈송이", url: "https://www.douclass.com/viewer/SPC_P/54620", len: "2:56" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 24, title: "버스 놀이", url: "https://www.douclass.com/viewer/SPC_P/54621", len: "1:07" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 25, title: "사랑의 마음", url: "https://www.douclass.com/viewer/SPC_P/54622", len: "2:20" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 26, title: "세계 여행", url: "https://www.douclass.com/viewer/SPC_P/54623", len: "1:38" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 27, title: "우리 집은 웃음바다", url: "https://www.douclass.com/viewer/SPC_P/54624", len: "3:24" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 28, title: "쑥쑥 자라라", url: "https://www.douclass.com/viewer/SPC_P/54625", len: "1:31" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 29, title: "아름다운 나라", url: "https://www.douclass.com/viewer/SPC_P/54626", len: "2:27" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 30, title: "도라지타령", url: "https://www.douclass.com/viewer/SPC_P/54627", len: "1:33" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 31, title: "모두 다 꽃이야", url: "https://www.douclass.com/viewer/SPC_P/54628", len: "1:46" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 32, title: "체체쿨레", url: "https://www.douclass.com/viewer/SPC_P/54630", len: "1:53" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 33, title: "초코라테 리듬 놀이", url: "https://www.douclass.com/viewer/SPC_P/54631", len: "1:46" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 34, title: "작은 세상(수어)", url: "https://www.douclass.com/viewer/SPC_P/54632", len: "1:31" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 35, title: "버터플라이(수어)", url: "https://www.douclass.com/viewer/SPC_P/54633", len: "1:41" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 36, title: "클라리넷 폴카", url: "https://www.douclass.com/viewer/SPC_P/54634", len: "0:57" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 37, title: "소고춤_기본 동작", url: "https://www.douclass.com/viewer/SPC_P/54635", len: "1:23" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 38, title: "소고춤_동작 익히기", url: "https://www.douclass.com/viewer/SPC_P/54636", len: "3:49" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 39, title: "소고춤(쾌지나칭칭나네)", url: "https://www.douclass.com/viewer/SPC_P/54637", len: "1:00" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 40, title: "웰컴 투 평창", url: "https://www.douclass.com/viewer/SPC_P/54639", len: "2:33" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 41, title: "빗방울들의 여행", url: "https://www.douclass.com/viewer/SPC_P/54638", len: "2:59" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 42, title: "탈춤(산도깨비)", url: "https://www.douclass.com/viewer/SPC_P/54640", len: "1:04" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 43, title: "탈춤_기본 동작", url: "https://www.douclass.com/viewer/SPC_P/54641", len: "1:36" },
  { group: "lesson", scope: "신체 표현", art: "body", no: 44, title: "봉산 탈춤_기본 동작", url: "https://www.douclass.com/viewer/SPC_P/54642", len: "5:06" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 1, title: "인사 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54644", len: "0:51" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 2, title: "동요 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54645", len: "0:49" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 3, title: "그림 단어 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54646", len: "1:00" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 4, title: "악기 소리 맞히기", url: "https://www.douclass.com/viewer/SPC_P/54647", len: "1:06" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 5, title: "전통 놀이 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54648", len: "1:01" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 6, title: "주변의 소리", url: "https://www.douclass.com/viewer/SPC_P/54649", len: "1:51" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 7, title: "직업 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54650", len: "1:00" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 8, title: "분류 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54651", len: "0:57" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 9, title: "단어 맞히기 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54652", len: "1:01" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 10, title: "움직이는 단어 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54653", len: "1:03" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 11, title: "인물 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54654", len: "1:02" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 12, title: "그림 추측 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54655", len: "1:14" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 13, title: "숨은 여권 찾기", url: "https://www.douclass.com/viewer/SPC_P/54656", len: "0:58" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 14, title: "추석 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54657", len: "1:21" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 15, title: "에너지 절약", url: "https://www.douclass.com/viewer/SPC_P/54658", len: "1:17" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 16, title: "세 고개 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54659", len: "1:06" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 17, title: "다섯 고개 퀴즈 1", url: "https://www.douclass.com/viewer/SPC_P/54660", len: "0:49" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 18, title: "다섯 고개 퀴즈 2", url: "https://www.douclass.com/viewer/SPC_P/54661", len: "1:04" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 19, title: "다섯 고개 퀴즈 3", url: "https://www.douclass.com/viewer/SPC_P/54662", len: "0:50" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 20, title: "난센스 퀴즈 1", url: "https://www.douclass.com/viewer/SPC_P/54663", len: "0:55" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 21, title: "난센스 퀴즈 2", url: "https://www.douclass.com/viewer/SPC_P/54664", len: "0:46" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 22, title: "난센스 퀴즈 3", url: "https://www.douclass.com/viewer/SPC_P/54665", len: "1:03" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 23, title: "난센스 퀴즈 4", url: "https://www.douclass.com/viewer/SPC_P/54666", len: "1:25" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 24, title: "봄 동식물 찾기", url: "https://www.douclass.com/viewer/SPC_P/54667", len: "1:08" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 25, title: "여름에 들을 수 있는 소리", url: "https://www.douclass.com/viewer/SPC_P/54668", len: "1:16" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 26, title: "연상 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54669", len: "1:01" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 27, title: "가을에 들을 수 있는 소리", url: "https://www.douclass.com/viewer/SPC_P/54670", len: "1:05" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 28, title: "가을 OX 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54671", len: "1:00" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 29, title: "낙엽 색깔 맞히기", url: "https://www.douclass.com/viewer/SPC_P/54672", len: "1:06" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 30, title: "단어 찾기 게임", url: "https://www.douclass.com/viewer/SPC_P/54673", len: "1:04" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 31, title: "겨울 단어 찾기", url: "https://www.douclass.com/viewer/SPC_P/54674", len: "1:33" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 32, title: "눈 결정 찾기", url: "https://www.douclass.com/viewer/SPC_P/54675", len: "1:17" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 33, title: "동작 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54677", len: "1:12" },
  { group: "lesson", scope: "퀴즈 타임", art: "quiz", no: 34, title: "날씨 퀴즈", url: "https://www.douclass.com/viewer/SPC_P/54676", len: "1:12" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 1, title: "노래 부를 때의 바른 자세와 호흡", url: "https://www.douclass.com/viewer/SPC_P/54678", len: "3:37", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 2, title: "소리를 듣고 표현하는 놀이하기", url: "https://www.douclass.com/viewer/SPC_P/54681", len: "4:31", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 3, title: "소리를 움직임으로 표현하기", url: "https://www.douclass.com/viewer/SPC_P/54682", len: "3:06", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 4, title: "빠르기 셈여림 변화를 몸으로 표현하기", url: "https://www.douclass.com/viewer/SPC_P/54683", len: "3:17", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 5, title: "타악기 소리를 움직임으로 표현하기", url: "https://www.douclass.com/viewer/SPC_P/60906", len: "3:04", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 6, title: "가락의 높이 표현하기(아름다운 나라)", url: "https://www.douclass.com/viewer/SPC_P/54684", len: "2:45", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 7, title: "봄의 소리 흉내 내기", url: "https://www.douclass.com/viewer/SPC_P/54685", len: "3:36", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 8, title: "가을의 소리 표현하기", url: "https://www.douclass.com/viewer/SPC_P/54686", len: "3:58", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 9, title: "흥부와 놀부 이야기 알아보고 표현하기", url: "https://www.douclass.com/viewer/SPC_P/60907", len: "4:44", tag: "표현하기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 10, title: "풍물놀이 책 만들기", url: "https://www.douclass.com/viewer/SPC_P/54693", len: "3:08", tag: "만들기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 11, title: "미래의 내 모습 그리기", url: "https://www.douclass.com/viewer/SPC_P/54689", len: "3:01", tag: "만들기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 12, title: "에그셰이커 만들기", url: "https://www.douclass.com/viewer/SPC_P/54688", len: "1:31", tag: "만들기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 13, title: "마라카스 만들기", url: "https://www.douclass.com/viewer/SPC_P/54690", len: "3:20", tag: "만들기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 14, title: "레인스틱 만들기", url: "https://www.douclass.com/viewer/SPC_P/54691", len: "3:29", tag: "만들기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 15, title: "귀로(기로) 만들기", url: "https://www.douclass.com/viewer/SPC_P/54692", len: "3:26", tag: "만들기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 16, title: "우유갑 흔들 북 만들기", url: "https://www.douclass.com/viewer/SPC_P/60917", len: "1:36", tag: "만들기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 17, title: "자연의 소리가 나는 악기 만들기", url: "https://www.douclass.com/viewer/SPC_P/60918", len: "1:08", tag: "만들기" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 18, title: "학교에 가면 놀이하기", url: "https://www.douclass.com/viewer/SPC_P/54680", len: "2:54", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 19, title: "일정박에 맞추어 자신을 소개하기", url: "https://www.douclass.com/viewer/SPC_P/54679", len: "1:22", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 20, title: "티니클링", url: "https://www.douclass.com/viewer/SPC_P/54694", len: "1:41", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 21, title: "풍물놀이 대형 만들기", url: "https://www.douclass.com/viewer/SPC_P/54695", len: "5:23", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 22, title: "강강술래 기본 동작(1)", url: "https://www.douclass.com/viewer/SPC_P/54696", len: "0:50", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 23, title: "강강술래 기본 동작(2)", url: "https://www.douclass.com/viewer/SPC_P/54697", len: "0:54", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 24, title: "강강술래-자진강강술래 놀이", url: "https://www.douclass.com/viewer/SPC_P/54698", len: "1:41", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 25, title: "대문놀이", url: "https://www.douclass.com/viewer/SPC_P/54699", len: "0:52", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 26, title: "손 치기 발치기", url: "https://www.douclass.com/viewer/SPC_P/54700", len: "0:37", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 27, title: "남생아 놀아라 놀이(1)", url: "https://www.douclass.com/viewer/SPC_P/54701", len: "0:27", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 28, title: "남생아 놀아라 놀이(2)", url: "https://www.douclass.com/viewer/SPC_P/54702", len: "0:26", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 29, title: "남생아 놀아라 놀이(3)", url: "https://www.douclass.com/viewer/SPC_P/54703", len: "2:43", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 30, title: "개고리 개골청 놀이", url: "https://www.douclass.com/viewer/SPC_P/54704", len: "0:27", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 31, title: "고사리꺾기 놀이(1)", url: "https://www.douclass.com/viewer/SPC_P/54706", len: "0:27", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 32, title: "고사리꺾기 놀이(2)", url: "https://www.douclass.com/viewer/SPC_P/54705", len: "1:51", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 33, title: "덕석몰이와 덕석풀기(1)", url: "https://www.douclass.com/viewer/SPC_P/54707", len: "0:28", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 34, title: "덕석몰이와 덕석풀기(2)", url: "https://www.douclass.com/viewer/SPC_P/54708", len: "1:44", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 35, title: "청어엮기와 청어풀기(1)", url: "https://www.douclass.com/viewer/SPC_P/54709", len: "0:33", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 36, title: "청어엮기와 청어풀이(2)", url: "https://www.douclass.com/viewer/SPC_P/54710", len: "2:49", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 37, title: "강강술래 놀이 익히기(전체)", url: "https://www.douclass.com/viewer/SPC_P/54643", len: "4:42", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 38, title: "강강술래 놀이(전체)", url: "https://www.douclass.com/viewer/SPC_P/54711", len: "2:16", tag: "음악놀이" },
  { group: "lesson", scope: "활동 영상", art: "activity", no: 39, title: "강강술래 다양한 놀이(전체)", url: "https://www.douclass.com/viewer/SPC_P/54712", len: "10:43", tag: "음악놀이" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 1, title: "큰북", url: "https://www.douclass.com/viewer/SPC_P/31204", len: "3:38" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 2, title: "작은북", url: "https://www.douclass.com/viewer/SPC_P/31205", len: "4:52" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 3, title: "탬버린", url: "https://www.douclass.com/viewer/SPC_P/31206", len: "2:52" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 4, title: "트라이앵글", url: "https://www.douclass.com/viewer/SPC_P/31275", len: "3:10" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 5, title: "마라카스", url: "https://www.douclass.com/viewer/SPC_P/31209", len: "1:51" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 6, title: "캐스터네츠", url: "https://www.douclass.com/viewer/SPC_P/31207", len: "2:17" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 7, title: "리듬 막대", url: "https://www.douclass.com/viewer/SPC_P/31208", len: "1:54" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 8, title: "우드블록", url: "https://www.douclass.com/viewer/SPC_P/31210", len: "2:44" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 9, title: "귀로", url: "https://www.douclass.com/viewer/SPC_P/31211", len: "2:28" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 10, title: "카바사", url: "https://www.douclass.com/viewer/SPC_P/31212", len: "1:57" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 11, title: "슬레이벨(슬라이스벨)", url: "https://www.douclass.com/viewer/SPC_P/31213", len: "1:52" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 12, title: "아고고 벨", url: "https://www.douclass.com/viewer/SPC_P/31214", len: "1:31" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 13, title: "심벌즈", url: "https://www.douclass.com/viewer/SPC_P/31215", len: "3:10" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 14, title: "마라카스 연주 방법", url: "https://www.douclass.com/viewer/SPC_P/60908", len: "0:55" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 15, title: "마라카스_매미의 노래", url: "https://www.douclass.com/viewer/SPC_P/60909", len: "2:03" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 16, title: "컵타_리듬과 동작", url: "https://www.douclass.com/viewer/SPC_P/31217", len: "0:28", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/99/8d/ac5f160e8af2ef82abcc4f6d6d38407dff4a/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 17, title: "컵타_When I'm Gone", url: "https://www.douclass.com/viewer/SPC_P/31219", len: "1:02", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/4f/78/5b0f9b9215cb28257fc1973d854ea4f4836b/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 18, title: "컵타_풍선", url: "https://www.douclass.com/viewer/SPC_P/45714", len: "1:48", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/27/b7/075cd50873b0e19d4c687b2975fad8d10583/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 19, title: "카혼_다양한 리듬", url: "https://www.douclass.com/viewer/SPC_P/31221", len: "0:34", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/e7/5e/bd5521fec87b197ffed7981d138347e0b2a2/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 20, title: "카혼_폰서트", url: "https://www.douclass.com/viewer/SPC_P/31277", len: "0:53", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/df/55/a19ec3291568e40d243876b01a98c37bd040/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 21, title: "드럼", url: "https://www.douclass.com/viewer/SPC_P/31216", len: "2:57" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 22, title: "드럼_다양한 리듬", url: "https://www.douclass.com/viewer/SPC_P/31223", len: "0:30", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/1b/0c/876776352a90f4c5b790812f1b532e552ef4/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 23, title: "드럼_I'll Be Missing You", url: "https://www.douclass.com/viewer/SPC_P/31225", len: "0:29", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/1f/f9/9f12507bfe2894e3dbaf3882443636ed5279/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "서양 타악기", art: "perc", no: 24, title: "드럼_여행을 떠나요", url: "https://www.douclass.com/viewer/SPC_P/31227", len: "1:17", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/8b/39/160dd876b67d87885ce8741fc25f6f1d917b/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 1, title: "소고", url: "https://www.douclass.com/viewer/SPC_P/31309", len: "1:08" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 2, title: "소고 연주 방법", url: "https://www.douclass.com/viewer/SPC_P/60910", len: "2:46" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 3, title: "소고_참새 노래", url: "https://www.douclass.com/viewer/SPC_P/46380", len: "0:38", sheetUrl: "https://s3.douclass.com/pub/2026/TC_ACTIVE/2608/ssgcf5yptlc9.pdf", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 4, title: "소고_왕도토리", url: "https://www.douclass.com/viewer/SPC_P/60911", len: "2:48" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 5, title: "소고_남생아 놀아라", url: "https://www.douclass.com/viewer/SPC_P/46381", len: "0:33", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/cc/1d/841d3b45873a351a64002ee99ff4624f7028/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 6, title: "소고_훨훨이", url: "https://www.douclass.com/viewer/SPC_P/46382", len: "0:58", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/cc/64/5341fdc559406a97e32359ead468bb69821e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 7, title: "장구", url: "https://www.douclass.com/viewer/SPC_P/31313", len: "2:03", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/43/a3/33bc646739ff330e61b39e4cf44bea2b15bc/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 8, title: "장구_여러 가지 장단", url: "https://www.douclass.com/viewer/SPC_P/31314", len: "1:47", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/f3/da/d08e32813b3f98f4a36fdd662e75e67217af/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 9, title: "장구_자진모리장단", url: "https://www.douclass.com/viewer/SPC_P/46522", len: "1:04", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/fd/20/63b49296a6af2fea63e9072c4b28a0ba8de7/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 10, title: "장구_세마치장단", url: "https://www.douclass.com/viewer/SPC_P/46523", len: "0:29", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/45/e9/6b78f132658e35fbd2cddae367ba02e52f73/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 11, title: "장구_굿거리장단", url: "https://www.douclass.com/viewer/SPC_P/46564", len: "0:48", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/27/1e/ebeb2559372fb4494c46ab98523c358ae18e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 12, title: "장구_중중모리장단", url: "https://www.douclass.com/viewer/SPC_P/46525", len: "0:52", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/d1/2e/92f9300162d1c0a9336d886371b706395a9e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 13, title: "장구_두꺼비집이 여물까(자진모리장단)", url: "https://www.douclass.com/viewer/SPC_P/31316", len: "1:45", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/ba/c9/437dfca0f5f9c4a4ab343df775e3b5ffba4d/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 14, title: "장구_실구대 소리(자진모리장단)", url: "https://www.douclass.com/viewer/SPC_P/31318", len: "2:00", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/d6/3b/31fd5c9d662ad6ee1c7aa6b570ee333b144a/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 15, title: "장구_나물노래(자진모리장단)", url: "https://www.douclass.com/viewer/SPC_P/46605", len: "0:46", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/aa/98/136d5066581e83a3e483910904b3fe2fc1f0/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 16, title: "장구_고사리꺾자(자진모리장단)", url: "https://www.douclass.com/viewer/SPC_P/44728", len: "1:32", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/6f/1b/3be4f95623a40b3366258ec302bd882a9913/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 17, title: "장구_개고리 개골청(자진모리장단)", url: "https://www.douclass.com/viewer/SPC_P/46456", len: "1:09", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/a8/39/17d6af1e0c301f0c56e6005fb0699ef6bf5e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 18, title: "장구_대문놀이(자진모리장단)", url: "https://www.douclass.com/viewer/SPC_P/46520", len: "1:03", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/74/9e/601f42480946ba464d47793c52a0303fcfd3/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 19, title: "장구_이거리저거리각거리(자진모리장단)", url: "https://www.douclass.com/viewer/SPC_P/46437", len: "0:43", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/ed/49/816e8e1ee1e1ead40e59138d491d2b8ecba2/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 20, title: "장구_도라지타령(세마치장단)", url: "https://www.douclass.com/viewer/SPC_P/31319", len: "1:18", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/45/bc/17de12c4fd1bf727af6347e74e085848b660/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 21, title: "장구_아리랑(세마치장단)", url: "https://www.douclass.com/viewer/SPC_P/46440", len: "0:53", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/03/98/1e6ea426d624e41b76d9a2b9dcc5fcabc2e0/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 22, title: "장구_늴리리야(굿거리장단)", url: "https://www.douclass.com/viewer/SPC_P/31321", len: "1:33", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/d7/68/bafe5576bffaed9936d9c56cc60f84f21866/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 23, title: "장구_거문도 뱃노래(굿거리장단)", url: "https://www.douclass.com/viewer/SPC_P/44729", len: "2:10", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/e5/9b/031f360e98b8354110fa821b74bbfbdad326/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 24, title: "장구_아침 해(굿거리장단)", url: "https://www.douclass.com/viewer/SPC_P/44730", len: "1:01", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/ce/46/105022e60d814445e7540e930763bea02f78/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 25, title: "장구_도움소 소리(중중모리장단)", url: "https://www.douclass.com/viewer/SPC_P/31320", len: "2:10", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/da/86/b8fae25cb19e5081c4af08c08293ab3c5145/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 26, title: "장구_둥당기타령(중중모리장단)", url: "https://www.douclass.com/viewer/SPC_P/44732", len: "2:01", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/51/d6/954a80c5376c1e24aacf93f860d012061272/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 27, title: "북", url: "https://www.douclass.com/viewer/SPC_P/31310", len: "2:02", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/03/c5/491f8fcb2428d6ed97d91be2508ba64d3d6e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 28, title: "꽹과리", url: "https://www.douclass.com/viewer/SPC_P/31311", len: "3:34", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/1b/86/dc03b58233de0c69acceafe16c3f407041bd/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 29, title: "징", url: "https://www.douclass.com/viewer/SPC_P/31312", len: "2:56", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/20/e5/1835026394ce63998775ef886943857ff45e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 30, title: "사물놀이_인사굿", url: "https://www.douclass.com/viewer/SPC_P/31315", len: "0:28", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/cf/f0/4c0da3efd140d9cdb09c271ca2a7e4c4eee9/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "국악 타악기", art: "jang", no: 31, title: "사물놀이_별달거리", url: "https://www.douclass.com/viewer/SPC_P/31317", len: "2:58", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/dd/34/eead29b2783fc081ac3a4994ea1e26dade17/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "건반 악기", art: "keys", no: 1, title: "실로폰", url: "https://www.douclass.com/viewer/SPC_P/31185", len: "3:31", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/0f/d8/ee74a1d8a2a089e8f20e57044f319c05139e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "건반 악기", art: "keys", no: 2, title: "실로폰_방울꽃", url: "https://www.douclass.com/viewer/SPC_P/31267", len: "0:53", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/4c/8b/b90b8631252086e3ad64d4f1a5f08a9f135c/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "건반 악기", art: "keys", no: 3, title: "멜로디언", url: "https://www.douclass.com/viewer/SPC_P/31187", len: "1:47", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/b5/d2/c921225e437d1fc16ecf7fd1c64bad432b6c/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "건반 악기", art: "keys", no: 4, title: "멜로디언_가을바람", url: "https://www.douclass.com/viewer/SPC_P/31189", len: "0:46", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/f5/be/7af82584b0e174829c2753c4bfdd339885e6/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "건반 악기", art: "keys", no: 5, title: "칼림바_다장조 음계", url: "https://www.douclass.com/viewer/SPC_P/31259", len: "0:53", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/dc/96/f4fd6523cf96b904983761dbe98a64bd6bcc/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "건반 악기", art: "keys", no: 6, title: "칼림바_할아버지의 낡은 시계", url: "https://www.douclass.com/viewer/SPC_P/31191", len: "0:48", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/f8/a4/e418052dd43c212c3ccbb35b0fe47111407f/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "건반 악기", art: "keys", no: 7, title: "피아노_다장조 음계", url: "https://www.douclass.com/viewer/SPC_P/31192", len: "0:18", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/7e/a4/147bce808e91a24a9868eaca15d4a496e97e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "건반 악기", art: "keys", no: 8, title: "피아노_Over the Rainbow", url: "https://www.douclass.com/viewer/SPC_P/31194", len: "0:55", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/7c/e0/50504b55c823a699f0ee3f637eaa28a3f59f/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 1, title: "리코더 (1)", url: "https://www.douclass.com/viewer/SPC_P/31069", len: "4:47", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/ba/33/92c00054d12e648ea63cd53cbfd9738652a2/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 2, title: "리코더 (2)", url: "https://www.douclass.com/viewer/SPC_P/31077", len: "3:57", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/bd/b8/ac3d51c5a4b793f2d70a800a9a1a4c0ee008/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 3, title: "둥근 빵", url: "https://www.douclass.com/viewer/SPC_P/46411", len: "0:31", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/73/78/25cdf4b553cd6d06b1863a6475171c718c26/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 4, title: "뻐꾸기", url: "https://www.douclass.com/viewer/SPC_P/46412", len: "0:42", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/38/f3/ceb4db41a80eb0e6e15f201a40e0904ef2f5/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 5, title: "잠자리", url: "https://www.douclass.com/viewer/SPC_P/46414", len: "0:46", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/57/bd/5bde97eaa2e1aea140b554eeb60199762902/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 6, title: "노르웨이 춤곡", url: "https://www.douclass.com/viewer/SPC_P/46410", len: "0:42", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/4b/da/506a248c5b12bff1b87a7ac3f6bafb7065fe/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 7, title: "겨울 나무", url: "https://www.douclass.com/viewer/SPC_P/44706", len: "1:12", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/01/e7/aba8f7af825489815d0af3e0602bf1eb701a/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 8, title: "별 보며 달 보며", url: "https://www.douclass.com/viewer/SPC_P/46499", len: "1:15", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/91/e1/3c580109cef3f91a9fc6d9591b2a8c2db6a7/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 9, title: "퍼프와 재키", url: "https://www.douclass.com/viewer/SPC_P/31062", len: "0:43", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/90/4a/aef9170d2f8c44fb2577a232b395eabc1a76/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 10, title: "퍼프와 재키 2중주(바로크)", url: "https://www.douclass.com/viewer/SPC_P/46519", len: "0:54", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/b3/87/2e75138074ad50eae2e3052598f1d9a9e516/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 11, title: "퍼프와 재키 2중주(저먼)", url: "https://www.douclass.com/viewer/SPC_P/46521", len: "0:54", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/5b/4e/69378c985e0dbd9dfb754515d30aa23a202d/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 12, title: "피노키오", url: "https://www.douclass.com/viewer/SPC_P/44708", len: "1:12", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/03/13/1187cbe4239c713cfd0806d522d0e5e064d8/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 13, title: "언제나 몇 번이라도 2중주", url: "https://www.douclass.com/viewer/SPC_P/44712", len: "1:26", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/8d/ad/284f1658214e71947f7cb5e3c8a0da964c3a/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 14, title: "언제나 몇 번이라도(위 성부)", url: "https://www.douclass.com/viewer/SPC_P/44713", len: "1:25", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/52/97/246af740c7bfafd7a8c68d05b4f70948b2de/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 15, title: "언제나 몇 번이라도(아래 성부)", url: "https://www.douclass.com/viewer/SPC_P/44714", len: "1:26", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/7e/cc/d6bc153873dffcc39a9a7d0c071c2213861e/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 16, title: "바람이 불어오는 곳", url: "https://www.douclass.com/viewer/SPC_P/44711", len: "0:58", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/2f/67/40ff55bf8af6ec5c4bc804f4e6c39db174a6/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 17, title: "우리의 꿈을 노래해", url: "https://www.douclass.com/viewer/SPC_P/44705", len: "0:56", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/7b/b7/6f6c217b4d39750499692ab8469216838e86/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 18, title: "할아버지의 시계 2중주", url: "https://www.douclass.com/viewer/SPC_P/44715", len: "1:22", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/b4/17/908d70e7f435ebdcdfcd43b485931434dfe2/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 19, title: "할아버지의 시계(위 성부)", url: "https://www.douclass.com/viewer/SPC_P/44716", len: "1:22", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/66/1c/81f7f241ac75a3bd4116303f6949216451e0/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 20, title: "할아버지의 시계(아래 성부)", url: "https://www.douclass.com/viewer/SPC_P/44717", len: "1:22", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/60/66/f08548347167e717fdc715027622f4995560/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 21, title: "위풍당당 행진곡(바로크)", url: "https://www.douclass.com/viewer/SPC_P/44709", len: "1:11", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/f8/63/c8959edaaee2be47f6307b502ce75798a279/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 22, title: "위풍당당 행진곡(저먼)", url: "https://www.douclass.com/viewer/SPC_P/44710", len: "1:12", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/8e/a4/70e2ae94cd5ee0b36f18f297d953b467515c/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 23, title: "&quot;행성&quot; 중 '목성'", url: "https://www.douclass.com/viewer/SPC_P/44707", len: "1:23", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/d1/83/7e2e576488a1a54cc3cc60c159919c3f4d19/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 24, title: "학교 가는 길", url: "https://www.douclass.com/viewer/SPC_P/31270", len: "1:29", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/d3/52/390f76bec6a241b56f6fc05f1485e47ba275/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 25, title: "바나나 차차", url: "https://www.douclass.com/viewer/SPC_P/31081", len: "0:28", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/e8/08/2efdd8853a4dbe6309d18ccece08f5fba858/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "리코더", art: "recorder", no: 26, title: "미뉴에트", url: "https://www.douclass.com/viewer/SPC_P/31086", len: "0:33", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/00/b6/6c400593fe532498991f0db9a4d8b62346a2/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 1, title: "단소 (1)", url: "https://www.douclass.com/viewer/SPC_P/31142", len: "3:36", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/86/e9/e4cdd0f85f02bc92cb214bb4af856e36d39b/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 2, title: "단소 (2)", url: "https://www.douclass.com/viewer/SPC_P/44718", len: "2:12", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/4b/52/4f1f2517ee5766dcf0fa8bc3890f347c86d5/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 3, title: "늴리리야 (단소)", url: "https://www.douclass.com/viewer/SPC_P/44721", len: "0:49", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/d9/4b/39e17a7e9bf932648ead8ef9a0a28b6e8fbd/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 4, title: "너영나영 (단소)", url: "https://www.douclass.com/viewer/SPC_P/44722", len: "0:47", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/53/87/da95c1cebff8464b354412c21c419261cdd4/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 5, title: "아침 해 (단소)", url: "https://www.douclass.com/viewer/SPC_P/44723", len: "0:58", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/c3/c6/624aa67a49470b56f58b2fdf3fa806902819/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 6, title: "아리랑 (단소)", url: "https://www.douclass.com/viewer/SPC_P/44720", len: "0:48", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/cc/4c/d32f23005f96a935348e8181a7f568afa086/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 7, title: "새야 새야 (단소)", url: "https://www.douclass.com/viewer/SPC_P/31146", len: "0:36", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/c2/c5/d307859236c9892d8f7b72af30303eb960b7/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 8, title: "오나라 (단소)", url: "https://www.douclass.com/viewer/SPC_P/31150", len: "0:49", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/35/58/1fe60999785cedff22ff8c9d141524c5d404/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 9, title: "계면 가락 도드리 (단소)", url: "https://www.douclass.com/viewer/SPC_P/31153", len: "0:39", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/2c/68/6127e479615a34f61acbeb98c355c8285f9d/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 10, title: "소금 (1)", url: "https://www.douclass.com/viewer/SPC_P/31244", len: "3:41", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/98/be/370151b578884e9c1a81dac1d8c8dcce9554/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 11, title: "소금 (2)", url: "https://www.douclass.com/viewer/SPC_P/44724", len: "2:02", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/44/97/2a4ec896d92a08b03eb25f954ec23bf70d6d/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 12, title: "나물노래 (소금)", url: "https://www.douclass.com/viewer/SPC_P/44726", len: "0:34", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/e9/a5/fafb70adcf2ea096f7816e4f86df4c5794e3/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 13, title: "벌아 벌아 꿀 떠라 (소금)", url: "https://www.douclass.com/viewer/SPC_P/44725", len: "0:21", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/14/ac/2e29d0e5293b6f7ef1c5b4fb84f3dce60ecf/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 14, title: "새야새야 (소금)", url: "https://www.douclass.com/viewer/SPC_P/47523", len: "0:29", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/f3/3e/8248e7673252f8c80308f884181da8d354b1/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 15, title: "아리랑 (소금)", url: "https://www.douclass.com/viewer/SPC_P/44727", len: "0:48", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/33/1a/8d8479f09d810fd7f59a6d9b3638a9856bfc/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 16, title: "이 거리 저 거리 각 거리 (소금)", url: "https://www.douclass.com/viewer/SPC_P/31248", len: "0:18", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/f7/7f/ef228b3fa38272ca807e0715f7a4fa1fcdf2/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 17, title: "상사화 (소금)", url: "https://www.douclass.com/viewer/SPC_P/31273", len: "0:33", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/60/b4/267fab50e69c9663ee5178187d7c0878b3ab/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "단소·소금", art: "danso", no: 18, title: "밀양 아리랑 (소금)", url: "https://www.douclass.com/viewer/SPC_P/31274", len: "0:39", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/fe/7f/fc35cfefa20b5989a8ccc16a6fdd383e8497/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 1, title: "기타", url: "https://www.douclass.com/viewer/SPC_P/31293", len: "3:32", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/d1/7e/20353ebf4e9d6f61c5e5cb59808b0907bab4/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 2, title: "기타 스트로크 주법", url: "https://www.douclass.com/viewer/SPC_P/31294", len: "0:48", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/8f/8b/3ab9bc8791a19a15db126c6e30bab5399d3a/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 3, title: "바람이 불어오는 곳 (기타)", url: "https://www.douclass.com/viewer/SPC_P/31296", len: "1:44", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/de/59/00a1b941a420946f5962aa9955d74d210d63/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 4, title: "You Are My Sunshine (기타)", url: "https://www.douclass.com/viewer/SPC_P/31297", len: "0:32", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/7d/43/c24f7239fd1604f41ee33d3a6b0d21a293ba/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 5, title: "You Raise Me Up (기타)", url: "https://www.douclass.com/viewer/SPC_P/31298", len: "1:16", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/58/1b/21de3e51e4e6cbf7923948a627f285c06a94/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 6, title: "먼지가 되어 (기타)", url: "https://www.douclass.com/viewer/SPC_P/31300", len: "2:53", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/9f/b6/7ef10088d4dc162f3200817435b037d7597c/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 7, title: "우쿨렐레", url: "https://www.douclass.com/viewer/SPC_P/31278", len: "6:20", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/1b/8b/324d6e75e7692ac313a421744fd23289e5de/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 8, title: "우쿨렐레 다장조 음계", url: "https://www.douclass.com/viewer/SPC_P/31279", len: "0:33", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/31/0e/84241977cf79b0d6cd5f97713d833d138456/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 9, title: "우쿨렐레 스트로크 주법", url: "https://www.douclass.com/viewer/SPC_P/31280", len: "0:42", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/c4/49/e39970d290b10176279a844ad3b49fb7fa7c/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 10, title: "제주도의 푸른 밤 (우쿨렐레)", url: "https://www.douclass.com/viewer/SPC_P/31291", len: "1:36", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/04/c1/33d9ceb6a08e6f4ddf8e1c1beaabef88733f/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 11, title: "여름 냇가 (우쿨렐레)", url: "https://www.douclass.com/viewer/SPC_P/31289", len: "0:24", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/7d/40/4c3ea6e9132c0238f897ea1a7f5f99d9f58c/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "기타·우쿨렐레", art: "guitar", no: 12, title: "조개 껍질 묶어 (우쿨렐레)", url: "https://www.douclass.com/viewer/SPC_P/31292", len: "0:54", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/67/b0/1e38965fdb2704e79f4b09cb1819dd67656a/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "가야금", art: "gaya", no: 1, title: "가야금", url: "https://www.douclass.com/viewer/SPC_P/31303", len: "2:27", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/35/eb/51ce902d67f5c5080fcdfd5e9feb78050276/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "가야금", art: "gaya", no: 2, title: "가야금 기본 주법", url: "https://www.douclass.com/viewer/SPC_P/31304", len: "0:37", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/66/98/1f9f9c88f22924972893315f4831890c9afa/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "가야금", art: "gaya", no: 3, title: "아리랑 (가야금)", url: "https://www.douclass.com/viewer/SPC_P/31306", len: "0:51", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/68/0a/91b6b464e34d4acd63e06d28d4052b92a2c9/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "inst", scope: "가야금", art: "gaya", no: 4, title: "도라지타령 (가야금)", url: "https://www.douclass.com/viewer/SPC_P/31308", len: "1:11", sheetUrl: "https://hermes.douclass.com/hermes/resource/store/49/6b/cc128ee72269c408aa173fae724ccf001508/hview.html", sheetLabel: "연주 악보 (pdf)" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 1, title: "종묘 제례악(해설)", url: "https://www.douclass.com/viewer/SPC_P/30152", len: "5:55", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 2, title: "종묘제례&종묘제례악 2부 세종이 만들고 세조가 완성한 종묘제례악", url: "https://www.douclass.com/viewer/SPC_P/30212", len: "8:00", tag: "기악-정악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 3, title: "종묘제례&종묘제례악 3부 전쟁은 악기도 숨게 한다", url: "https://www.douclass.com/viewer/SPC_P/30213", len: "7:14", tag: "기악-정악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 4, title: "수제천(해설)", url: "https://www.douclass.com/viewer/SPC_P/30153", len: "3:22", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 5, title: "여민락(해설)", url: "https://www.douclass.com/viewer/SPC_P/51903", tag: "기악-정악", source: "국립국악원/전통예술공연진흥원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 6, title: "영산회상(해설)", url: "https://www.douclass.com/viewer/SPC_P/30157", len: "5:14", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 7, title: "천년만세(해설)", url: "https://www.douclass.com/viewer/SPC_P/51905", tag: "기악-정악", source: "국립국악원/전통예술공연진흥원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 8, title: "취타와 대취타(해설)", url: "https://www.douclass.com/viewer/SPC_P/30151", len: "5:12", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 9, title: "대취타(해설)", url: "https://www.douclass.com/viewer/SPC_P/60278", len: "5:12", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 10, title: "대풍류(해설)", url: "https://www.douclass.com/viewer/SPC_P/51908", tag: "기악-정악", source: "국립국악원/전통예술공연진흥원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 11, title: "대금 독주 청성자진한잎(해설)", url: "https://www.douclass.com/viewer/SPC_P/51906", tag: "기악-정악", source: "국립국악원/전통예술공연진흥원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 12, title: "높은 음으로 듣는 가곡, 청성자진한잎 - 대금·단소 비교하며 들어보기", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1712&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 13, title: "생소병주 수룡음(해설)", url: "https://www.douclass.com/viewer/SPC_P/51907", tag: "기악-정악", source: "국립국악원/전통예술공연진흥원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 14, title: "산조(해설)", url: "https://www.douclass.com/viewer/SPC_P/51909", tag: "기악-민속악", source: "국립국악원/전통예술공연진흥원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 15, title: "산조(해설)", url: "https://www.douclass.com/viewer/SPC_P/30155", len: "7:09", tag: "기악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 16, title: "문화재 돋보기 - 거문고 산조", url: "https://www.douclass.com/viewer/SPC_P/30196", len: "2:30", tag: "기악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 17, title: "시나위(해설)", url: "https://www.douclass.com/viewer/SPC_P/30154", len: "3:03", tag: "기악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 18, title: "신명과 화합의 한마당, 농악", url: "https://www.douclass.com/viewer/SPC_P/30203", len: "4:51", tag: "기악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 19, title: "흥 넘치는 전통, 농악", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1738&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "기악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 20, title: "흥겨운 풍물놀이", url: "https://www.douclass.com/viewer/SPC_P/60905", len: "1:19", tag: "기악-민속악", source: "두클래스" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 21, title: "사물놀이(해설)", url: "https://www.douclass.com/viewer/SPC_P/30144", len: "4:20", tag: "민속 신앙 의식 및 창작 국악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 22, title: "사물놀이 사총사, 서로 다른 소리들이 만나 이루는 아름다운 하모니", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1831&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "민속 신앙 의식 및 창작 국악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 23, title: "같은 듯 다른 음악, 농악과 사물놀이 - 사물놀이의 탄생", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1826&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "민속 신앙 의식 및 창작 국악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 24, title: "사물놀이 장단 중 별달거리장단 들어보기", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1833&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "민속 신앙 의식 및 창작 국악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 25, title: "가곡과 시조(해설)", url: "https://www.douclass.com/viewer/SPC_P/30156", len: "5:21", tag: "성악-정악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 26, title: "풍류 문화의 백미, 가곡", url: "https://www.douclass.com/viewer/SPC_P/30215", len: "7:23", tag: "성악-정악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 27, title: "판소리(해설)", url: "https://www.douclass.com/viewer/SPC_P/30147", len: "4:03", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 28, title: "판소리 다섯 마당", url: "https://www.douclass.com/viewer/SPC_P/30201", len: "7:17", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 29, title: "한국의 문화유산 - 판소리", url: "https://www.douclass.com/viewer/SPC_P/30200", len: "3:07", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 30, title: "판소리 소개 - 어린이용 영상", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1767&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 31, title: "판소리 다섯마당 - 어린이용 영상", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1770&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 32, title: "판소리를 난생 처음 들은 세대별 반응은?(feat. 유태평양 명창)", url: "https://www.douclass.com/viewer/SPC_P/45169", len: "17:14", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 33, title: "민요(해설)", url: "https://www.douclass.com/viewer/SPC_P/51910", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 34, title: "제주민요", url: "https://www.douclass.com/viewer/SPC_P/45167", len: "22:39", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 35, title: "경기민요x대중가요(이춘희x안예은)", url: "https://www.douclass.com/viewer/SPC_P/30186", len: "8:44", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 36, title: "전쟁 그리고 아리랑", url: "https://www.douclass.com/viewer/SPC_P/30192", len: "4:42", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 37, title: "삶의 노래, 정선 아리랑", url: "https://www.douclass.com/viewer/SPC_P/30191", len: "7:00", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 38, title: "아리랑 1부 민족의 소리 아리랑", url: "https://www.douclass.com/viewer/SPC_P/30189", len: "6:57", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 39, title: "한국의 노래, 아리랑", url: "https://www.douclass.com/viewer/SPC_P/30188", len: "4:58", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 40, title: "아리랑 2부 삶의 노래, 3대 아리랑", url: "https://www.douclass.com/viewer/SPC_P/30190", len: "6:33", tag: "성악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 41, title: "궁중 무용(해설)", url: "https://www.douclass.com/viewer/SPC_P/30149", len: "6:52", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 42, title: "포구락(해설)", url: "https://www.douclass.com/viewer/SPC_P/51904", tag: "무용 및 연회", source: "국립국악원/전통예술공연진흥원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 43, title: "처용무", url: "https://www.douclass.com/viewer/SPC_P/60352", len: "7:27", tag: "무용 및 연회", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 44, title: "악운을 쫓는 궁중무용, 처용무 - 5·5·5로 보는 처용무의 상징", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1729&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 45, title: "봉산탈춤 - 탈로 전하는 삶과 풍자", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1737&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 46, title: "평등하지 않던 세상의 분출구, 탈춤과 가면놀이", url: "https://www.douclass.com/viewer/SPC_P/30216", len: "5:15", tag: "무용 및 연회", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 47, title: "강강술래는 왜 대보름에 추었을까", url: "https://www.douclass.com/viewer/SPC_P/30187", len: "6:51", tag: "무용 및 연회", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 48, title: "신과 인간의 축제, 대관령 강릉단오제", url: "https://www.douclass.com/viewer/SPC_P/30211", len: "7:37", tag: "민속 신앙 의식 및 창작 국악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 49, title: "한국의 공연 예술, 농악", url: "https://www.douclass.com/viewer/SPC_P/30202", len: "4:02", tag: "기악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 50, title: "자유로운 영혼, 지친 삶을 위로하다, 안성남사당풍물놀이", url: "https://www.douclass.com/viewer/SPC_P/45166", len: "3:10", tag: "민속 신앙 의식 및 창작 국악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 51, title: "곰뱅이 텄다! 남사당놀이", url: "https://www.douclass.com/viewer/SPC_P/30204", len: "7:09", tag: "민속 신앙 의식 및 창작 국악", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 52, title: "SHOW ME THE 문화유산 - 조선 후기 서민 문화", url: "https://www.douclass.com/viewer/SPC_P/30217", len: "2:34", tag: "국악 일반 및 악기 해설", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 53, title: "유기장, 두드려 징을 만들다", url: "https://www.douclass.com/viewer/SPC_P/45164", len: "19:36", tag: "국악 일반 및 악기 해설", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 54, title: "악기장, 천년의 울림을 만들다", url: "https://www.douclass.com/viewer/SPC_P/45162", len: "5:34", tag: "국악 일반 및 악기 해설", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 55, title: "대금장, 대금을 만들다", url: "https://www.douclass.com/viewer/SPC_P/30198", len: "14:08", tag: "국악 일반 및 악기 해설", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 56, title: "악기장, 12줄이 만드는 진한 울림", url: "https://www.douclass.com/viewer/SPC_P/30197", len: "3:43", tag: "국악 일반 및 악기 해설", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 57, title: "한국의 문화유산 - 가야금", url: "https://www.douclass.com/viewer/SPC_P/30199", len: "3:19", tag: "국악 일반 및 악기 해설", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 58, title: "문화재 돋보기 - 북", url: "https://www.douclass.com/viewer/SPC_P/30193", len: "2:40", tag: "국악 일반 및 악기 해설", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 59, title: "문화재 돋보기 - 나발", url: "https://www.douclass.com/viewer/SPC_P/45161", len: "4:33", tag: "국악 일반 및 악기 해설", source: "국가유산채널" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 60, title: "국악 현악기 한눈에 보기 - 구조·주법·음색과 합주 감상까지", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1837&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 61, title: "국악 관악기 한눈에 보기 - 구조·주법·음색과 합주 감상까지", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1839&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 62, title: "국악 타악기 한눈에 보기 - 구조·주법·음색과 합주 감상까지", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1846&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 63, title: "크기는 작아도 소리는 강하다! 피리의 모든 것", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1800&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 64, title: "사물놀이의 대장, 꽹과리 이야기", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1803&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 65, title: "장단의 중심, 장구 이야기", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1804&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 66, title: "악기들을 잔잔히 감싸는 울림, 징", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1813&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 67, title: "한쪽 면으로 만드는 사물놀이의 심장 소리, 풍물북", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1811&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 68, title: "대금과 피리로 들어보는 아리랑", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1819&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "개념 영상", art: "concept", no: 69, title: "가야금·거문고·아쟁·해금으로 듣는 아리랑", url: "https://academy.gugak.go.kr/open/open/lecture/detail.do?openLectureSeq=1816&srchOpenCategorySeq=17&srchListType=CATEGORY&currentMenuId=900006001", tag: "국악 일반 및 악기 해설", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 1, title: "종묘 제례악", url: "https://www.douclass.com/viewer/SPC_P/30173", len: "11:45", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 2, title: "문묘 제례악", url: "https://www.douclass.com/viewer/SPC_P/30174", len: "14:43", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 3, title: "수제천", url: "https://www.douclass.com/viewer/SPC_P/30131", len: "7:56", tag: "기악-정악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 4, title: "수제천", url: "https://www.douclass.com/viewer/SPC_P/30181", len: "17:23", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 5, title: "여민락", url: "https://www.douclass.com/viewer/SPC_P/30183", len: "11:33", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 6, title: "보허자", url: "https://www.douclass.com/viewer/SPC_P/30184", len: "9:07", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 7, title: "낙양춘", url: "https://www.douclass.com/viewer/SPC_P/50757", len: "9:16", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 8, title: "취타", url: "https://www.douclass.com/viewer/SPC_P/30172", len: "5:46", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 9, title: "대취타", url: "https://www.douclass.com/viewer/SPC_P/30133", len: "4:08", tag: "기악-정악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 10, title: "대취타", url: "https://www.douclass.com/viewer/SPC_P/30171", len: "4:28", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 11, title: "평조회상", url: "https://www.douclass.com/viewer/SPC_P/50790", len: "51:06", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 12, title: "평조회상 중 타령·군악", url: "https://www.douclass.com/viewer/SPC_P/30132", len: "7:52", tag: "기악-정악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 13, title: "관악 영산회상", url: "https://www.douclass.com/viewer/SPC_P/50756", len: "22:31", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 14, title: "관악 영산회상 중 상영산", url: "https://www.douclass.com/viewer/SPC_P/50747", len: "10:13", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 15, title: "현악 영산회상", url: "https://www.douclass.com/viewer/SPC_P/51020", len: "46:54", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 16, title: "현악 영산회상 중 상영산", url: "https://www.douclass.com/viewer/SPC_P/51016", len: "9:17", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 17, title: "현악 영산회상 중 하현 도드리", url: "https://www.douclass.com/viewer/SPC_P/51019", len: "3:07", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 18, title: "현악 영산회상 중 하현 도드리, 염불도드리, 타령", url: "https://www.douclass.com/viewer/SPC_P/51018", len: "10:50", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 19, title: "현악 영산회상 중 타령", url: "https://www.douclass.com/viewer/SPC_P/51017", len: "3:05", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 20, title: "현악 영산회상 중 별곡", url: "https://www.douclass.com/viewer/SPC_P/51015", len: "55:29", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 21, title: "현악 영산회상 중 군악", url: "https://www.douclass.com/viewer/SPC_P/50792", len: "3:58", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 22, title: "천년만세", url: "https://www.douclass.com/viewer/SPC_P/30182", len: "9:54", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 23, title: "천년만세 중 우조 가락 도드리", url: "https://www.douclass.com/viewer/SPC_P/50776", len: "3:06", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 24, title: "천년만세 중 양청도드리", url: "https://www.douclass.com/viewer/SPC_P/50774", len: "2:43", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 25, title: "천년만세 중 계면 가락 도드리", url: "https://www.douclass.com/viewer/SPC_P/50771", len: "3:43", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 26, title: "생소병주_수룡음", url: "https://www.douclass.com/viewer/SPC_P/30178", len: "5:20", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 27, title: "단소 독주_청성곡", url: "https://www.douclass.com/viewer/SPC_P/50760", len: "7:01", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 28, title: "대금 독주_청성곡", url: "https://www.douclass.com/viewer/SPC_P/30177", len: "6:36", tag: "기악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 29, title: "청성자진한잎", url: "https://www.douclass.com/viewer/SPC_P/30134", len: "5:33", tag: "기악-정악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 30, title: "가야금 산조 (성금연류)", url: "https://www.douclass.com/viewer/SPC_P/30136", len: "7:30", tag: "기악-민속악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 31, title: "가야금 산조", url: "https://www.douclass.com/viewer/SPC_P/30175", len: "9:34", tag: "기악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 32, title: "해금 산조 (지영희류)", url: "https://www.douclass.com/viewer/SPC_P/30137", len: "6:53", tag: "기악-민속악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 33, title: "시나위", url: "https://www.douclass.com/viewer/SPC_P/50764", len: "11:25", tag: "기악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 34, title: "농악_판굿", url: "https://www.douclass.com/viewer/SPC_P/50759", len: "13:11", tag: "기악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 35, title: "사물놀이", url: "https://www.douclass.com/viewer/SPC_P/30141", len: "7:17", tag: "민속 신앙 의식 및 창작 국악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 36, title: "사물놀이", url: "https://www.douclass.com/viewer/SPC_P/30162", len: "9:59", tag: "민속 신앙 의식 및 창작 국악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 37, title: "풍물놀이", url: "https://www.douclass.com/viewer/SPC_P/30161", len: "8:42", tag: "기악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 38, title: "남창가곡_우조 초수대엽", url: "https://www.douclass.com/viewer/SPC_P/30180", len: "9:45", tag: "성악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 39, title: "여창가곡_우락", url: "https://www.douclass.com/viewer/SPC_P/30179", len: "6:57", tag: "성악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 40, title: "시조_동창이", url: "https://www.douclass.com/viewer/SPC_P/50784", len: "5:22", tag: "성악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 41, title: "시조_태산이", url: "https://www.douclass.com/viewer/SPC_P/50765", len: "7:59", tag: "성악-정악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 42, title: "청산리 (평시조)", url: "https://www.douclass.com/viewer/SPC_P/30135", len: "4:04", tag: "성악-정악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 43, title: "아리랑", url: "https://www.douclass.com/viewer/SPC_P/30169", len: "9:21", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 44, title: "강원도 아리랑", url: "https://www.douclass.com/viewer/SPC_P/30170", len: "3:34", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 45, title: "해주 아리랑", url: "https://www.douclass.com/viewer/SPC_P/50791", len: "1:20", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 46, title: "진도 아리랑", url: "https://www.douclass.com/viewer/SPC_P/50768", len: "3:50", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 47, title: "밀양 아리랑", url: "https://www.douclass.com/viewer/SPC_P/50761", len: "1:20", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 48, title: "남도 민요", url: "https://www.douclass.com/viewer/SPC_P/30140", len: "5:20", tag: "성악-민속악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 49, title: "경기 민요", url: "https://www.douclass.com/viewer/SPC_P/30139", len: "5:14", tag: "성악-민속악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 50, title: "판소리_춘향가 중 사랑가", url: "https://www.douclass.com/viewer/SPC_P/30168", len: "5:43", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 51, title: "춘향가 중 사랑가 (판소리)", url: "https://www.douclass.com/viewer/SPC_P/30138", len: "3:13", tag: "성악-민속악", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 52, title: "판소리_수궁가 중 범 내려오는 대목", url: "https://www.douclass.com/viewer/SPC_P/31345", len: "6:19", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 53, title: "판소리_수궁가 중 토끼 화상 그리는 대목", url: "https://www.douclass.com/viewer/SPC_P/30167", len: "4:24", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 54, title: "판소리_수궁가 중 토끼화상 그리는 대목", url: "https://www.douclass.com/viewer/SPC_P/50763", len: "4:39", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 55, title: "판소리_흥보가 중 화초장", url: "https://www.douclass.com/viewer/SPC_P/30166", len: "6:58", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 56, title: "판소리_흥보가 중 박타령", url: "https://www.douclass.com/viewer/SPC_P/30165", len: "7:27", tag: "성악-민속악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 57, title: "평택농악", url: "https://www.douclass.com/viewer/SPC_P/60481", len: "8:49", tag: "기악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 58, title: "이리농악", url: "https://www.douclass.com/viewer/SPC_P/60474", len: "8:57", tag: "기악-민속악", source: "국가유산채널" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 59, title: "춘앵전", url: "https://www.douclass.com/viewer/SPC_P/50778", len: "9:18", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 60, title: "오양선", url: "https://www.douclass.com/viewer/SPC_P/50767", len: "20:34", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 61, title: "포구락", url: "https://www.douclass.com/viewer/SPC_P/30163", len: "7:43", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 62, title: "처용무", url: "https://www.douclass.com/viewer/SPC_P/48905", len: "10:22", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 63, title: "강강술래", url: "https://www.douclass.com/viewer/SPC_P/30160", len: "6:35", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 64, title: "봉산 탈춤", url: "https://www.douclass.com/viewer/SPC_P/50762", len: "14:14", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 65, title: "부채춤", url: "https://www.douclass.com/viewer/SPC_P/30142", len: "5:42", tag: "무용 및 연회", source: "국악방송" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 66, title: "소고 춤", url: "https://www.douclass.com/viewer/SPC_P/30158", len: "4:06", tag: "무용 및 연회", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 67, title: "봉산탈춤", url: "https://www.douclass.com/viewer/SPC_P/60454", len: "6:06", tag: "무용 및 연회", source: "국가유산채널" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 68, title: "북청사자놀음", url: "https://www.douclass.com/viewer/SPC_P/60460", len: "6:11", tag: "무용 및 연회", source: "국가유산채널" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 69, title: "강령탈춤", url: "https://www.douclass.com/viewer/SPC_P/60449", len: "4:13", tag: "무용 및 연회", source: "국가유산채널" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 70, title: "은율탈춤", url: "https://www.douclass.com/viewer/SPC_P/60464", len: "3:11", tag: "무용 및 연회", source: "국가유산채널" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 71, title: "영산재_작법", url: "https://www.douclass.com/viewer/SPC_P/50766", len: "16:32", tag: "민속 신앙 의식 및 창작 국악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 72, title: "침향무(황병기)", url: "https://www.douclass.com/viewer/SPC_P/30176", len: "9:33", tag: "민속 신앙 의식 및 창작 국악", source: "국립국악원" },
  { group: "gugak", scope: "연주 영상", art: "perform", no: 73, title: "청소년을 위한 국악 관현악 입문", url: "https://www.douclass.com/viewer/SPC_P/30143", len: "37:05", tag: "민속 신앙 의식 및 창작 국악", source: "국악방송" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 1, title: "사물놀이 VS 풍물놀이의 차이는?", url: "https://www.douclass.com/viewer/SPC_P/30108", len: "3:11", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 2, title: "사물놀이에서 우두머리는 무엇이다?", url: "https://www.douclass.com/viewer/SPC_P/30109", len: "3:35", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 3, title: "발에 탈을 쓰고 하는 놀이도 있다?", url: "https://www.douclass.com/viewer/SPC_P/30110", len: "3:22", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 4, title: "춤은 무엇으로 현재까지 전승된다?!", url: "https://www.douclass.com/viewer/SPC_P/30111", len: "3:51", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 5, title: "정말 명창들은 피를 토하면서 득음했을까?", url: "https://www.douclass.com/viewer/SPC_P/30113", len: "3:28", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 6, title: "종묘제례악의 작곡가는 음악가가 아닌 누구이다?!", url: "https://www.douclass.com/viewer/SPC_P/30114", len: "3:43", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 7, title: "남사당패는 있고 여사당패는 없다?!", url: "https://www.douclass.com/viewer/SPC_P/30115", len: "3:23", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 8, title: "김홍도 무동의 비밀", url: "https://www.douclass.com/viewer/SPC_P/30116", len: "3:42", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 9, title: "왜 가야금은 금이고 거문고는 고일까?", url: "https://www.douclass.com/viewer/SPC_P/30118", len: "3:38", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 10, title: "해금은 현악기일까 관악기일까?", url: "https://www.douclass.com/viewer/SPC_P/30119", len: "3:30", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 11, title: "국악기 중 철사로 현을 만든 유일한 악기가 있다?", url: "https://www.douclass.com/viewer/SPC_P/30120", len: "3:38", source: "국가유산채널" },
  { group: "gugak", scope: "국악, 이것은 알고 가자", art: "trivia", no: 12, title: "이순신장군은 고통을 잊기 위해 무엇을 했다?!", url: "https://www.douclass.com/viewer/SPC_P/30121", len: "3:31", source: "국가유산채널" },
];
